site_name: PyAuxLib
repo_url: https://github.com/psolsfer/PyAuxLib
repo_name: PyAuxLib

site_dir: site

theme:
    name: material
    language: en
    #logo: assets/logo.png
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: indigo
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.instant
        - navigation.sections
        - navigation.tracking
        - content.tabs.link
        - toc.follow
        - navigation.top

markdown_extensions:
    - pymdownx.highlight:
          linenums: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - pymdownx.blocks.definition
    - pymdownx.blocks.details
    # - pymdownx.blocks.tab

    - markdown.extensions.toc:
          baselevel: 2
          permalink: true
        #   slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}



plugins:
    - include-markdown
    - mkdocstrings
    - awesome-pages
    - search:
          lang: en
extra:
    version:
        provider: mike
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/psolsfer
          name: Github
        - icon: material/email
          link: "mailto:psolsfer@gmail.com"
